# Environment
export PATH=$HOME/bin:$PATH
export EDITOR=vim

# fix color escape sequences showing up in less.
export LESS=-eiMXR

# If set, bash checks the window size after each command and, if necessary,
# updates the values of LINES and COLUMNS.
shopt -s checkwinsize

display_venv() {
    if [ ! -z $VIRTUAL_ENV ]; then
        venv=$(basename $VIRTUAL_ENV)
        python_version=$(basename $(dirname $VIRTUAL_ENV))
        echo "$python_version($venv)"
    fi
}

display_git_branch() {
    if git show-ref --quiet 2> /dev/null; then
        local BRANCH=$(git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/^\*\ //')
        if [ -n "${BRANCH}" ]; then
            echo "(${BRANCH})"
        fi
    fi
}

git_ps1() {
    local red=$(tput setaf 1)
    local green=$(tput setaf 2)
    local cyan=$(tput setaf 6)
    local blue=$(tput setaf 4)
    local clr=$(tput sgr0)

    export PS1="$clr
\d \@ $green\u${clr}@$cyan\h$clr:$PWD $red$(display_venv)$clr
$(display_git_branch)$ "
}

export PROMPT_COMMAND="git_ps1"

# make command line behave more like vi
set -o vi

# History
HISTCONTROL=ignoredups:ignorespace
HISTSIZE=10000
HISTFILESIZE=100000
shopt -s histappend
bind '"\e[B": history-search-forward'
bind '"\e[A": history-search-backward'

# source alias file
if [ -f $HOME/.bash_aliases ]; then
    source $HOME/.bash_aliases
fi
