# ls in mac different from linux
if [[ `uname` == 'Linux' ]]; then
   alias ls='ls --color=auto --group-directories-first'
elif [[ `uname` == 'Darwin' ]]; then
      alias ls='ls -G'
fi

# I never want the old vi
alias vi='vim'
# Always show the full path not the symlink I followed
alias cd='cd -P'

# make things interactive
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# grep
alias igrep='egrep -r -n --color --exclude-dir="*.git*" --binary-files="without-match"'

# version control
alias gl='git log --graph --decorate'
alias gg='git log --graph --oneline --boundary @{u}..'
